packages = [
    "plasma-desktop",
    "dolphin",
    "gwenview",
    "konsole",
    "ttf-dejavu",
    "sddm",
    "sddm-kcm",
    "plasma-nm",
    "pipewire",
    "pipewire-pulse",
    "pipewire-alsa",
    "wireplumber",
    "xdg-user-dirs",
    "xdg-utils",
]
script = """
set -exu

systemctl enable sddm
"""
