packages = []
script = """
set -exu

cat << 'EOF' >> /etc/pacman.conf
[archzfs]
SigLevel = Required
Server = https://github.com/archzfs/archzfs/releases/download/experimental
EOF

pacman-key --recv-keys 3A9917BF0DED5C13F69AC68FABEC0A1208037BE9
pacman-key --lsign-key 3A9917BF0DED5C13F69AC68FABEC0A1208037BE9

pacman -S --needed --noconfirm linux-headers
pacman -Sy zfs-dkms
"""
